Fri Mar  2 19:49:10 CET 2012
Linux ucouchbase 3.0.0-13-server #22-Ubuntu SMP Wed Nov 2 15:09:08 UTC 2011 x86_64 x86_64 x86_64 GNU/Linux
tests.test_01_database.TestConnection.test_01_create_database ... ok
tests.test_01_database.TestConnection.test_02_drop_database ... ok
tests.test_01_database.TestConnection.test_03_check_views ... ok
tests.test_01_database.TestDatabase.test_01_view_unprocessed_docs ... ok
tests.test_01_database.TestDatabase.test_02_delitem_contains ... ok
tests.test_01_database.TestDatabase.test_03_save_get_image ... ok
tests.test_02_process_images.TestProcessImages.test_01_process_images ... ok
tests.test_02_process_images.TestProcessImages.test_02_exception_handling ... ok
tests.test_03_thread_pool.TestThreadPool.test_02_custom_worker ... ok

----------------------------------------------------------------------
Ran 9 tests in 10.976s

OK
Exception in thread Thread-50 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/home/wache/GrafServer/virtual_envs-Linux/shared/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/home/wache/GrafServer/graf/thread_pool.py", line 19, in run
  File "/home/wache/GrafServer/virtual_envs-Linux/shared/lib/python2.7/Queue.py", line 168, in get
  File "/home/wache/GrafServer/virtual_envs-Linux/shared/lib/python2.7/threading.py", line 237, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
